### ISSUE TITLE
Not reproducible

### ISSUE THREAD

**Issue by ivan-m** [fpco/weigh#10]
Trying to use the internals of weigh as a library, I have the following:

```haskell
{-# LANGUAGE GADTs, RankNTypes #-}

import Weigh (weighFunc)
import Control.DeepSeq (NFData)
import Data.Int (Int64)

-- | The results from measuring memory usage.
data GetWeight where
  GetWeight :: forall a b. (NFData b) => (a -> b) -> a -> GetWeight

runGetWeight :: GetWeight -> IO Weight
runGetWeight (GetWeight f a) = (\(b,gc,_,_) -> Weight b gc) <$> weighFunc f a

data Weight = Weight { bytesAlloc :: !Int64
                     , numGC      :: !Int64
                     }
            deriving (Eq, Ord, Show, Read)
```

Trying to use this in ghci:

```haskell
λ> import qualified Data.ByteString as SB
λ> let w = GetWeight (SB.length . SB.pack) (replicate 1000000 0)
λ> runGetWeight w
Weight {bytesAlloc = 57000096, numGC = 1}
λ> runGetWeight w
Weight {bytesAlloc = 1001280, numGC = 0}
λ> runGetWeight w
Weight {bytesAlloc = 1001280, numGC = 0}
λ> runGetWeight w
Weight {bytesAlloc = 1001472, numGC = 0}
λ> runGetWeight w
Weight {bytesAlloc = 1001280, numGC = 0}
λ> runGetWeight w
Weight {bytesAlloc = 1001280, numGC = 0}
```

(The `1001472` case is odd, but this exact chain of results is reproducible.)

My best guess is that this occurs due to caching or something like that; I actually have this occuring when trying to use my above snippet of code after running tests or criterion benchmarks; they don't refer to the `GetWeight` type, but are constructed from the same functions and values that are passed to it.

**Comment by chrisdone** [comment]
This is why weigh's main entry point runs each test as a separate program so that it's reproducible.  With the following

```haskell
-- | Weigh integers.
main :: IO ()
main =
  mainWith (func "ivan test" (SB.length . SB.pack) (replicate 1000000 0))
```

I get this every time:

```
Case                              Allocated  GCs         Max
ivan test                        49,000,096   91  23,999,952
```

**Comment by ivan-m** [comment]
So it's not possible to use weigh as a library without the `mainWith` function?

**Comment by chrisdone** [comment]
I don't know of a way to do it.

**Comment by ivan-m** [comment]
Note also that this requires having the same function/variable being re-evaluated as well; if I do something as simple as creating a new `GetWeight` value then running it, then it works.
