### ISSUE TITLE
Measured bytes differs from what is reported by a cost center

### ISSUE THREAD

**Issue by ocharles** [fpco/weigh#14]
I'm working with the following:

```haskell
module Main (main) where

import Weigh
import Data.IORef.Unboxed hiding (Counter)

main :: IO ()
main = do
  refu <- newIORefU (0 :: Int)
  mainWith $ do
    io "modifyIORefU" (\r -> {-# SCC modify #-} modifyIORefU r (+ 1)) refu
```

`weigh` reports that modifyIORefU allocates 48 bytes. However, if I actually run with `--case modifyIORefU foo +RTS -T -Pa`, GHC tells me that `modify` (the SCC) allocates 0 bytes. I'm not sure which to believe, but I'm more inclined to believe GHC. I'm working with unboxed IO refs (from `unboxed-refs`), so I don't believe I'm left with unevaluated thunks - being unboxed the IO ref is naturally strict in what it contains.

As an aside, interestingly just adding a {-# SCC #-} causes the reported allocations to go up, so I'm probably measuring the cost of profiling. Maybe a limitation of the library.

**Comment by chrisdone** [comment]
What does it report without profiling on?

**Comment by chrisdone** [comment]
On my machine it reports:
```
Case          Allocated  GCs
modifyIORefU          0    0
```

So probably profiling itself is captured by weigh. If I run with `stack test --profile`, then I get

```
Case          Allocated  GCs
modifyIORefU         48    0
```

Perhaps I can just add to the docs that profiling and weigh are incompatible?

**Comment by ocharles** [comment]
> Perhaps I can just add to the docs that profiling and weigh are incompatible?

Seems worth a mention.

**Comment by chrisdone** [comment]
I wonder whether I could detect it with GHC runtime information... then I could issue a warning message.
