### ISSUE TITLE
Why direct build-depend on TemplateHaskell ?

### ISSUE THREAD

**Issue by nobrakal** [fpco/weigh#18]
Hi,

Why weigh as a build depend on TemplateHaskell ? It effectively depend on it trough `temporary`, who depend on `exceptions`, who depend on TH, but I can't see any TH-related code in weigh...

**Comment by chrisdone** [comment]
Maybe it did at one point? Does it build if you comment out template-haskell in the .cabal file?

**Comment by nobrakal** [comment]
The only reference of TH is in `src/Weigh/GHCStats.hs`, with `{-# LANGUAGE TemplateHaskell #-}`.

So yeah, it build if you comment this and the field in `.cabal`

**Comment by chrisdone** [comment]
Would you mind opening a PR for that and I'll merge it?
