### ISSUE TITLE
Organize Weigh measures

### ISSUE THREAD

**Issue by nobrakal** [fpco/weigh#20]
Hi,

I want to benchmark graph libraries size, I have a _lot_ of benchmarks to do and I want to organize them. I cannot organize them "by hand" like in the example in the README, because I want my tests to be in different files (a file for a library).

Is something possible to handle this case ? I like the way `Criterion` handle that (with `bgroup`), because I can after navigate through groups, and sort them by their name for example. I don't know if it is possible with the current implementation of Weigh...

**Comment by chrisdone** [comment]
I agree, I was thinking about adding groups today.

**Comment by nobrakal** [comment]
I have started to look at it. I come to something like:
```Haskell
data ToWeight = Simple String Action | Group String [ToWeight]

-- | Weigh specification monad.
newtype Weigh a =
  Weigh {runWeigh :: State (Config, [ToWeight]) a}
  deriving (Monad,Functor,Applicative)

[...]

-- | Write out an action.
tellAction :: String -> Action -> Weigh ()
tellAction name action = Weigh $ modify $ second $ \x -> x ++ [Simple name action]

wgroup :: String -> Weigh () -> Weigh ()
wgroup str wei = do
  start <- Weigh get
  let startL = length $ snd start
  wei
  Weigh $ modify $ second $ \x -> take startL x ++ [Group str $ drop startL x]
```

Not very beautiful, but I think this can do the trick. There can be a syntax like:
```Haskell
mainWith $ do
  wgroup "fst" $ do
    func "1" f 1
    func "2" f 2
  wgroup "snd" $ do
    func "3" f 3
```

**Comment by chrisdone** [comment]
I like this direction. I'll try applying it today or tomorrow and see how it scales. Presumably nesting works correctly too?

**Comment by nobrakal** [comment]
Great :D
I can't see why nested wgroup will not work, but this definitely needs to be tested ^^

**Comment by chrisdone** [comment]
Implemented! http://hackage.haskell.org/package/weigh-0.0.8/docs/Weigh.html#v:wgroup
