### ISSUE TITLE
Error when using with criterion

### ISSUE THREAD

**Issue by nobrakal** [fpco/weigh#22]
```Haskell
import Criterion.Main (defaultMain)
import Weigh (mainWith)

main :: IO ()
main = do
  defaultMain []
  mainWith $ func "f" ((++) "a") "b"
```

is failing with error:

```
Error in case ("f"):
  Invalid option `--case'

Usage: containers [-I|--ci CI] [-L|--time-limit SECS] [--resamples COUNT]
                  [--regress RESP:PRED..] [--raw FILE] [-o|--output FILE]
                  [--csv FILE] [--json FILE] [--junit FILE]
                  [-v|--verbosity LEVEL] [-t|--template FILE]
                  ([-m|--match MATCH] [NAME...] | [-n|--iters ITERS]
                  [-m|--match MATCH] [NAME...] | [-l|--list] | [--version])

CallStack (from HasCallStack):
  error, called at src/Weigh.hs:340:12 in weigh-0.0.11-E2ZrXVWrFMK988oLKQqdc:Weigh
```

Note that the interchanging the order (using `defaultMain` after `mainWith`) produce the same thing. And commenting one line or the other run without problems.

**Comment by chrisdone** [comment]
Weigh works by launching a fresh pipe of the same executable and passing in which case to run (`--case`). Criterion is interpreting the arguments too. I just run benchmarks in a different executable.

For this to work you'd probably need a way to ask `weigh` if this is a forked process or the top-level process, and then you could decide not to run criterion's `defaultMain` on this run.

**Comment by chrisdone** [comment]
Relatedly we could change weigh to set an environment variable instead of passing in program arguments. That would be less intrusive. But it wouldn't fix that criterion would run for every weigh case.

**Comment by nobrakal** [comment]
Ok, I see, so this is not a "bug".

Maybe providing some information about it in the documentation can help to understand the problem ^^.

It is not very complicated then to write something than reason over `getArgs`, and run criterion if and only if there is no "--case" arguments.

But I agree with you, an environment variable can be less intrusive (as well as allowing a "--case" parameter for the rest of the software).

**Comment by mathandley** [comment]
For anyone's info: I was experiencing similar to the above while running Criterion and Weigh in the same IO function:

```
main :: IO () 
main  = do 
  defaultMain bs 
  mainWith w 

where 
  w :: Weigh ()
  w = ...
  bs :: [Benchmark]
  bs = ...
```

As explained above, this executes `defaultMain bs` for every case in `w`. I prevented this from happening by simply checking for the existence of the environment variable Weigh uses before executing the Criterion benchmarks. Something like:

```
main :: IO () 
main  = do 
  lookupEnv "WEIGH_CASE" >>= \case
     Nothing -> defaultMain bs
     Just{}    -> return ()
  mainWith w 
```

**Comment by chrisdone** [comment]
Another option is splitting the memory tests from the time benchmarks, which is my common practice. Specifically because weigh's results are reproducible and can be used as a test suite via `validateFunc`, etc. So I do e.g. `stack test :memory` vs `stack bench :time`
