### ISSUE TITLE
Export reportGroup

### ISSUE THREAD

**Issue by nobrakal** [fpco/weigh#25]
Hi,

I would love to use the results provided by `weighResults`, in a very similar way of `reportGroup`. Do you think it can be exported ?
The only problem I see, it that will lead to expose `Config` and `Format` data structure, and can expand a lot the export list.

(-Edit-) Or do something like the `setColumn` method, exposing only `Format`

Or maybe use separated files, to distinct formatting export of the rest ?

**Comment by chrisdone** [comment]
I'm fine with exposing those two types.

**Comment by nobrakal** [comment]
I see a little conflict with exposing `Config` and `setColumns` and maybe the bundled `Config` in the `Weigh` monad. Maybe a `setFormat` is better, and is coherent with the rest of `Weigh`.

**Comment by nobrakal** [comment]
Fixed :)
