### ISSUE TITLE
Writing output results in parse error

### ISSUE THREAD

**Issue by bokesan** [fpco/weigh#3]
Parsing the output from forked processes fails when you do output yourself, e.g.:

    main = do putStrLn "Hello!"
              mainWith (do ...

will fail with

    program: Prelude.read: no parse

I don't think that this necessarily needs to be fixed, but it certainly should be documented.

**Comment by chrisdone** [comment]
Perhaps a cheap solution is to write the output to a temp file, rather than communicate via stdout.

**Comment by chrisdone** [comment]
I put in a more descriptive error message for now.

**Comment by chrisdone** [comment]
I changed it to write to a temporary file instead in 0.0.4.
