### ISSUE TITLE
Meaning of "Live" column different for GHC versions 8.2 and later

### ISSUE THREAD

**Issue by agrue** [fpco/weigh#34]
Great library, very useful! I was trying to use it to measure the size of a large data structure, but the value in the "Live" column was much larger than I expected. Browsing the repo history, I saw that when `weigh` was updated to support GHC 8.2, the source of this value was changed from `currentBytesUsed` in `GCStats` to `cumulative_live_bytes` in `RTSStats`. However, the former represents "Number of live bytes at the end of the last major GC" while the latter represents "Sum of live bytes across all major GCs". So newer versions of GHC will report larger values (depending on the number of major GCs). e.g. I have an example that produces this for GHC 8.0.2:

```
Case   Allocated  GCs        Live         Max
blah  80,000,000  153  39,999,688  39,999,688
```

And this for GHC 8.2.2:

```
Case   Allocated  GCs         Live         Max
blah  80,000,000   76  126,204,912  39,999,752
```

(I can share the source if it's helpful). Both interpretations could be useful, but to be consistent with older versions of both GHC and `weigh` it seems like the value should instead come from `gcdetails_live_bytes` for the most recent `GCDetails` (i.e. `gcdetails_live_bytes . gc`). When I make this change the "Live" and "Max" columns have the same value again in GHC 8.2.

If you agree with this change I can prepare a PR.

**Comment by chrisdone** [comment]
Good catch. That sounds good, thanks!
