### ISSUE TITLE
Results depending on function ordering

### ISSUE THREAD

**Issue by Magalame** [fpco/weigh#37]
Hi!

First of all this is an amazing library! There is no say in how useful it is to analyze stream fusion

Secondly, I'm having a pretty bad problem. Consider this:
```haskell
module Main where

import qualified Statistics.Matrix as M
import           Statistics.Matrix (Matrix (..))

import qualified Data.Vector.Unboxed         as U
import           Data.Vector.Unboxed         (Vector)

import qualified System.Random.MWC as Mwc

import qualified Weigh         as W 

n :: Int
n = 100

testVector :: IO (Vector Double)
testVector = do 
    gen <- Mwc.create
    Mwc.uniformVector gen (n*n)


testMatrix :: IO Matrix
testMatrix = do
    vec <- testVector
    return $ Matrix n n vec


innerProduct :: Vector Double -> Vector Double -> Double
innerProduct u v = U.sum $ U.zipWith (*) u v

colm :: Int -> Matrix -> Vector Double
colm j m = U.generate n (\i -> v `U.unsafeIndex` (j + i * n))
  where v = _vector m 
{-# INLINE colm #-}

colv :: Int -> Vector Double -> Vector Double
colv j v = U.generate n (\i -> v `U.unsafeIndex` (j + i * n))
{-# INLINE colv #-}


weight :: Vector Double -> Matrix  -> IO ()
weight v a  = do
    W.mainWith (do 
        W.func "innerProduct vector" (innerProduct (colv 0 v)) (colv 0 v)
        W.func "innerProduct matrix" (innerProduct (colm 0 a)) (colm 0 a)
        )
main :: IO ()
main = do
    v <- testVector
    a <- testMatrix

    putStrLn "---Benchmarking memory consumption---"
    weight v a
```

gives:
```
---Benchmarking memory consumption---     
                                          
Case                   Allocated  GCs     
innerProduct vector          864    0     
innerProduct matrix         16    0   
```
However, if we swap the "innerProduct vector" line with the "innerProduct matrix" line, we have:
```
---Benchmarking memory consumption---     
                                          
Case                   Allocated  GCs     
innerProduct matrix        864    0     
innerProduct vector           16    0 
```

So in one case, the `vector` case allocates 16 bytes, in the other it allocates 16. I'm not sure where it is due to `weigh` itself, or some arcane feature of GHC, but in either case it is a tad worrying.

**Comment by chrisdone** [comment]
You're probably measuring allocation of the matrix. Before `mainWith` runs, all your resources needed for your test should be fully deepseq'd, if you don't want to include their allocations in the measurements.

**Comment by chrisdone** [comment]
Do e.g. `!a <- fmap force testVector` to force things deeply.

**Comment by Magalame** [comment]
Actually that's exactly what I'm trying to do! I.e. measure stream fusion is triggered, and doesn't allocate the full matrix

**Comment by chrisdone** [comment]
In that case I would allocate the data structure within an `io` action instead.

**Comment by chrisdone** [comment]
By the way, you can measure the allocation first. So you would have four tests.

1. One to measure allocation of the vector.
2. One to measure allocation of the matrix.
2. One to run your inner product on the vector.
2. One to run your inner product on the matrix.

That way you can compute the diff of the first two off of the last two.
