### ISSUE TITLE
mainWith cannot be used more than once

### ISSUE THREAD

**Issue by nineonine** [fpco/weigh#44]
This program
```
main IO ()
main = do
  mainWith someWeighAction1
  mainWith someWeighAction2
```
will crash with
```
No such case!
```

I know, it is rather obvious and the name kind of implies it should be used only once (main, duh). I am not sure what to do with it, perhaps the docs can be updated.

I just wanted to leave it here.

**Comment by nineonine** [comment]
Actually the same applies to `weighResults` as well!

**Comment by chrisdone** [comment]
Closing as obvious.

**Comment by nineonine** [comment]
while `mainWith` is somewhat obvious, I can't say that `weighResults` is.
