### ISSUE TITLE
Somewhat confusing results

### ISSUE THREAD

**Issue by nineonine** [fpco/weigh#45]
I have a program that looks like that:
```
main = do
  mainWith $ do
    action "io1" io1
    action "io2" io2
    action "io3" io3
```
It returns 
```
Case  Allocated             GCs
io1     3,409,611,320    2,062
io2     9,096,608           8
io3     8,399,944           7
```

However, when I do this

```
main = do
  io1
  io2
  io2
  mainWith $ do
    action "io1" io1
    action "io2" io2
    action "io3" io3
```
I get this
```
Case  Allocated             GCs
io1     2,154,904,000    2,062
io2     6,503,280           5
io3     2,777,026,064    2,657
```
The latter seems more real (because I know that `io3` requires a lot of memory.

What is going on here? I guess I am missing some important detail and don't quite understand the ideas that power the library.

**Comment by chrisdone** [comment]
weigh re-runs the current executable for each action. Therefore in your second example, `io1`, `io2`, `io2` are run before running the target action. 

I imagine some I/O is simply not performed twice, and this probably explains your results.

**Comment by nineonine** [comment]
I also noticed that when I am weighing IO actions, these action are not being executed. I guess this is expected. 
So I am thinking maybe this explains it - in my first example I am just weighing thunks but in my second example I run my actions which will evaluate and make necessary allocations along the way.

**Comment by nineonine** [comment]
Actually, I am not sure why this code:
```
main = do
  mainWith $ do
    action "hello" (putStrLn "hello")
```
does not perform any side affects

**Comment by chrisdone** [comment]
It performs the side effects in a piped process. So you won't see anything printed to stdout.
