### ISSUE TITLE
Is it possible to add some sort of "max residency" statistics?

### ISSUE THREAD

**Issue by mrkkrp** [fpco/weigh#8]
As I understand currently the library displays total number of allocated bytes. With streaming approach this number may be misleading, as it may appear as if memory consuption is significant, but max residency could be indeed still low. If we display max residency info along with the info weigh already displays, it may help detect memory leaks perhaps?

**Comment by chrisdone** [comment]
I've implemented this. You can now write:

```haskell
main =
  mainWith (do setColumns [Case, Allocated, GCs, Max]
            ...
```

to configure the columns. And the `Weight` type has `weightMaxBytes`.
